
inv:
  main:
    title: '&x&0&0&C&1&F&FМ&x&0&8&B&4&F&Eе&x&1&0&A&7&F&Eн&x&1&8&9&9&F&Dю&x&2&0&8&C&F&C &x&2&8&7&F&F&Bп&x&3&1&7&2&F&Bр&x&3&9&6&4&F&Aи&x&4&1&5&7&F&9в&x&4&9&4&A&F&8а&x&5&1&3&D&F&8т&x&5&9&2&F&F&7о&x&6&1&2&2&F&6в'
    items:
      BLUE_STAINED_GLASS_PANE:
        slots: [0, 1, 7, 8, 9, 17, 27, 35, 36, 37, 43, 44]
        name: ' '
        lore:
          - '&x&0&0&C&1&F&FП&x&0&4&B&A&F&Fр&x&0&9&B&3&F&Eи&x&0&D&A&B&F&Eв&x&1&2&A&4&F&Dе&x&1&6&9&D&F&Dт&x&1&A&9&6&F&D!&x&1&F&8&E&F&C &x&2&3&8&7&F&CЗ&x&2&8&8&0&F&Bд&x&2&C&7&9&F&Bе&x&3&1&7&2&F&Bс&x&3&5&6&A&F&Aь&x&3&9&6&3&F&A &x&3&E&5&C&F&9т&x&4&2&5&5&F&9ы&x&4&7&4&D&F&8 &x&4&B&4&6&F&8м&x&4&F&3&F&F&8о&x&5&4&3&8&F&7ж&x&5&8&3&0&F&7е&x&5&D&2&9&F&6ш&x&6&1&2&2&F&6ь'
          - '&x&0&0&C&1&F&FН&x&0&4&B&B&F&Fа&x&0&8&B&4&F&Eс&x&0&C&A&E&F&Eт&x&1&0&A&8&F&Eр&x&1&3&A&1&F&Dо&x&1&7&9&B&F&Dи&x&1&B&9&4&F&Cт&x&1&F&8&E&F&Cь&x&2&3&8&8&F&C &x&2&7&8&1&F&Bс&x&2&B&7&B&F&Bв&x&2&F&7&5&F&Bо&x&3&2&6&E&F&Aй&x&3&6&6&8&F&A &x&3&A&6&2&F&Aп&x&3&E&5&B&F&9р&x&4&2&5&5&F&9и&x&4&6&4&F&F&9в&x&4&A&4&8&F&8а&x&4&E&4&2&F&8т&x&5&1&3&B&F&7 &x&5&5&3&5&F&7д&x&5&9&2&F&F&7а&x&5&D&2&8&F&6ж&x&6&1&2&2&F&6е'
          - '&x&0&0&C&1&F&FН&x&0&4&B&A&F&Fе&x&0&9&B&3&F&E &x&0&D&A&B&F&Eи&x&1&2&A&4&F&Dс&x&1&6&9&D&F&Dп&x&1&A&9&6&F&Dо&x&1&F&8&E&F&Cл&x&2&3&8&7&F&Cь&x&2&8&8&0&F&Bз&x&2&C&7&9&F&Bо&x&3&1&7&2&F&Bв&x&3&5&6&A&F&Aа&x&3&9&6&3&F&Aт&x&3&E&5&C&F&9ь&x&4&2&5&5&F&9 &x&4&7&4&D&F&8к&x&4&B&4&6&F&8о&x&4&F&3&F&F&8м&x&5&4&3&8&F&7а&x&5&8&3&0&F&7н&x&5&D&2&9&F&6д&x&6&1&2&2&F&6!'
          - ''
        active: ''
      NETHERITE_SWORD:
        slots: [20]
        name: ' '
        lore:
          - '&x&0&0&C&1&F&FМ&x&0&6&B&6&F&Eа&x&0&D&A&C&F&Eг&x&1&3&A&1&F&Dа&x&1&A&9&7&F&Dз&x&2&0&8&C&F&Cи&x&2&7&8&1&F&Bн&x&2&D&7&7&F&B &x&3&4&6&C&F&Aэ&x&3&A&6&2&F&Aф&x&4&1&5&7&F&9ф&x&4&7&4&C&F&8е&x&4&E&4&2&F&8к&x&5&4&3&7&F&7т&x&5&B&2&D&F&7о&x&6&1&2&2&F&6в'
          - ''
          - '&x&0&0&C&1&F&FТ&x&0&3&B&C&F&Fу&x&0&6&B&7&F&Eт&x&0&9&B&3&F&E &x&0&C&A&E&F&Eт&x&0&F&A&9&F&Eы&x&1&2&A&4&F&D &x&1&5&9&F&F&Dм&x&1&8&9&A&F&Dо&x&1&A&9&6&F&Dж&x&1&D&9&1&F&Cе&x&2&0&8&C&F&Cш&x&2&3&8&7&F&Cь&x&2&6&8&2&F&B &x&2&9&7&E&F&Bк&x&2&C&7&9&F&Bу&x&2&F&7&4&F&Bп&x&3&2&6&F&F&Aи&x&3&5&6&A&F&Aт&x&3&8&6&5&F&Aь&x&3&B&6&1&F&A &x&3&E&5&C&F&9н&x&4&1&5&7&F&9о&x&4&4&5&2&F&9в&x&4&7&4&D&F&8ы&x&4&9&4&9&F&8е&x&4&C&4&4&F&8 &x&4&F&3&F&F&8э&x&5&2&3&A&F&7ф&x&5&5&3&5&F&7ф&x&5&8&3&0&F&7е&x&5&B&2&C&F&7к&x&5&E&2&7&F&6т&x&6&1&2&2&F&6ы'
          - '&x&0&0&C&1&F&FД&x&0&5&B&8&F&Fл&x&0&B&A&F&F&Eя&x&1&0&A&7&F&E &x&1&6&9&E&F&Dс&x&1&B&9&5&F&Dв&x&2&0&8&C&F&Cо&x&2&6&8&3&F&Cе&x&2&B&7&A&F&Bг&x&3&1&7&2&F&Bо&x&3&6&6&9&F&A &x&3&B&6&0&F&Aр&x&4&1&5&7&F&9е&x&4&6&4&E&F&9г&x&4&B&4&5&F&8и&x&5&1&3&D&F&8о&x&5&6&3&4&F&7н&x&5&C&2&B&F&7а&x&6&1&2&2&F&6!'
          - ''
        active: 'ShopRegion'
      ALLAY_SPAWN_EGG:
        slots: [ 22 ]
        name: ' '
        lore:
          - '&x&0&0&C&1&F&F&lИ&x&0&5&B&9&F&F&lн&x&0&A&B&1&F&E&lф&x&0&F&A&9&F&E&lо&x&1&3&A&1&F&D&lр&x&1&8&9&9&F&D&lм&x&1&D&9&1&F&C&lа&x&2&2&8&9&F&C&lц&x&2&7&8&1&F&B&lи&x&2&C&7&9&F&B&lя&x&3&1&7&2&F&B&l &x&3&5&6&A&F&A&lо&x&3&A&6&2&F&A&l &x&3&F&5&A&F&9&lр&x&4&4&5&2&F&9&lе&x&4&9&4&A&F&8&lг&x&4&E&4&2&F&8&lи&x&5&2&3&A&F&7&lо&x&5&7&3&2&F&7&lн&x&5&C&2&A&F&6&lе&x&6&1&2&2&F&6&l:'
          - ''
          - '&x&0&0&C&1&F&FК&x&0&A&B&1&F&Eо&x&1&3&A&1&F&Dо&x&1&D&9&1&F&Cр&x&2&7&8&1&F&Bд&x&3&1&7&2&F&Bи&x&3&A&6&2&F&Aн&x&4&4&5&2&F&9а&x&4&E&4&2&F&8т&x&5&7&3&2&F&7ы&x&6&1&2&2&F&6: %x%, %y%, %z%'
          - '&x&0&0&C&1&F&FВ&x&0&C&A&D&F&Eл&x&1&8&9&9&F&Dа&x&2&4&8&5&F&Cд&x&3&1&7&2&F&Bе&x&3&D&5&E&F&9л&x&4&9&4&A&F&8е&x&5&5&3&6&F&7ц&x&6&1&2&2&F&6: %owner%'
          - '&x&0&0&C&1&F&FП&x&0&A&B&1&F&Eр&x&1&3&A&1&F&Dо&x&1&D&9&1&F&Cч&x&2&7&8&1&F&Bн&x&3&1&7&2&F&Bо&x&3&A&6&2&F&Aс&x&4&4&5&2&F&9т&x&4&E&4&2&F&8и&x&5&7&3&2&F&7:&x&6&1&2&2&F&6 %durability%'
          - ''
        active: 'CloseMenu'
        regionInfo: true
      TOTEM_OF_UNDYING:
        slots: [ 24 ]
        name: ' '
        lore:
          - '&x&0&0&C&1&F&FМ&x&0&6&B&6&F&Eа&x&0&D&A&C&F&Eг&x&1&3&A&1&F&Dа&x&1&A&9&7&F&Dз&x&2&0&8&C&F&Cи&x&2&7&8&1&F&Bн&x&2&D&7&7&F&B &x&3&4&6&C&F&Aэ&x&3&A&6&2&F&Aф&x&4&1&5&7&F&9ф&x&4&7&4&C&F&8е&x&4&E&4&2&F&8к&x&5&4&3&7&F&7т&x&5&B&2&D&F&7о&x&6&1&2&2&F&6в'
          - ''
          - '&x&0&0&C&1&F&FТ&x&0&3&B&C&F&Fу&x&0&6&B&7&F&Eт&x&0&9&B&3&F&E &x&0&C&A&E&F&Eт&x&0&F&A&9&F&Eы&x&1&2&A&4&F&D &x&1&5&9&F&F&Dм&x&1&8&9&A&F&Dо&x&1&A&9&6&F&Dж&x&1&D&9&1&F&Cе&x&2&0&8&C&F&Cш&x&2&3&8&7&F&Cь&x&2&6&8&2&F&B &x&2&9&7&E&F&Bк&x&2&C&7&9&F&Bу&x&2&F&7&4&F&Bп&x&3&2&6&F&F&Aи&x&3&5&6&A&F&Aт&x&3&8&6&5&F&Aь&x&3&B&6&1&F&A &x&3&E&5&C&F&9н&x&4&1&5&7&F&9о&x&4&4&5&2&F&9в&x&4&7&4&D&F&8ы&x&4&9&4&9&F&8е&x&4&C&4&4&F&8 &x&4&F&3&F&F&8э&x&5&2&3&A&F&7ф&x&5&5&3&5&F&7ф&x&5&8&3&0&F&7е&x&5&B&2&C&F&7к&x&5&E&2&7&F&6т&x&6&1&2&2&F&6ы'
          - '&x&0&0&C&1&F&FД&x&0&5&B&8&F&Fл&x&0&B&A&F&F&Eя&x&1&0&A&7&F&E &x&1&6&9&E&F&Dс&x&1&B&9&5&F&Dв&x&2&0&8&C&F&Cо&x&2&6&8&3&F&Cе&x&2&B&7&A&F&Bг&x&3&1&7&2&F&Bо&x&3&6&6&9&F&A &x&3&B&6&0&F&Aр&x&4&1&5&7&F&9е&x&4&6&4&E&F&9г&x&4&B&4&5&F&8и&x&5&1&3&D&F&8о&x&5&6&3&4&F&7н&x&5&C&2&B&F&7а&x&6&1&2&2&F&6!'
          - ''
        active: 'SettingsRegion'
  shop:
    title: '&x&0&0&C&1&F&FМ&x&0&8&B&4&F&Eе&x&1&0&A&7&F&Eн&x&1&8&9&9&F&Dю&x&2&0&8&C&F&C &x&2&8&7&F&F&Bп&x&3&1&7&2&F&Bр&x&3&9&6&4&F&Aи&x&4&1&5&7&F&9в&x&4&9&4&A&F&8а&x&5&1&3&D&F&8т&x&5&9&2&F&F&7о&x&6&1&2&2&F&6в'
    items:
      BLUE_STAINED_GLASS_PANE:
        slots: [ 0 ]
        name: ' '
        lore:
          - '&x&0&0&C&1&F&FП&x&0&4&B&A&F&Fр&x&0&9&B&3&F&Eи&x&0&D&A&B&F&Eв&x&1&2&A&4&F&Dе&x&1&6&9&D&F&Dт&x&1&A&9&6&F&D!&x&1&F&8&E&F&C &x&2&3&8&7&F&CЗ&x&2&8&8&0&F&Bд&x&2&C&7&9&F&Bе&x&3&1&7&2&F&Bс&x&3&5&6&A&F&Aь&x&3&9&6&3&F&A &x&3&E&5&C&F&9т&x&4&2&5&5&F&9ы&x&4&7&4&D&F&8 &x&4&B&4&6&F&8м&x&4&F&3&F&F&8о&x&5&4&3&8&F&7ж&x&5&8&3&0&F&7е&x&5&D&2&9&F&6ш&x&6&1&2&2&F&6ь'
          - '&x&0&0&C&1&F&FН&x&0&4&B&B&F&Fа&x&0&8&B&4&F&Eс&x&0&C&A&E&F&Eт&x&1&0&A&8&F&Eр&x&1&3&A&1&F&Dо&x&1&7&9&B&F&Dи&x&1&B&9&4&F&Cт&x&1&F&8&E&F&Cь&x&2&3&8&8&F&C &x&2&7&8&1&F&Bс&x&2&B&7&B&F&Bв&x&2&F&7&5&F&Bо&x&3&2&6&E&F&Aй&x&3&6&6&8&F&A &x&3&A&6&2&F&Aп&x&3&E&5&B&F&9р&x&4&2&5&5&F&9и&x&4&6&4&F&F&9в&x&4&A&4&8&F&8а&x&4&E&4&2&F&8т&x&5&1&3&B&F&7 &x&5&5&3&5&F&7д&x&5&9&2&F&F&7а&x&5&D&2&8&F&6ж&x&6&1&2&2&F&6е'
          - '&x&0&0&C&1&F&FН&x&0&4&B&A&F&Fе&x&0&9&B&3&F&E &x&0&D&A&B&F&Eи&x&1&2&A&4&F&Dс&x&1&6&9&D&F&Dп&x&1&A&9&6&F&Dо&x&1&F&8&E&F&Cл&x&2&3&8&7&F&Cь&x&2&8&8&0&F&Bз&x&2&C&7&9&F&Bо&x&3&1&7&2&F&Bв&x&3&5&6&A&F&Aа&x&3&9&6&3&F&Aт&x&3&E&5&C&F&9ь&x&4&2&5&5&F&9 &x&4&7&4&D&F&8к&x&4&B&4&6&F&8о&x&4&F&3&F&F&8м&x&5&4&3&8&F&7а&x&5&8&3&0&F&7н&x&5&D&2&9&F&6д&x&6&1&2&2&F&6!'
          - ''
        active: ''


blocks:
  EMERALD_ORE:
    holograms:
      enable: true
      height: 1.55
      lines:
        - '#fb1f3aБ#fb2937о#fb3234л#fc3c31ь#fc452eш#fc4f2bо#fc5928й #fc6224п#fc6c21р#fd751eи#fd7f1bв#fd8818а#fd9215т'
        - '&fПрочность: &6%durability%'
        - '&fВладелец: &6%player%'
      visible-range: 30
    settings:
      durability: 2
      max-durability: 10
      create-lightning-strike: true
      delete-lightning-strike: true
      merge-regions: true
      block-piston: true
      explosions: true
      exclusion-explosions-types: []
      use-spawn-eggs: true
      falling-block-allow: true
      destroy-block-region: true
      block-change-wither: true
      hook-up-mine-cart-hopper: true
      open-mine-cart-hopper: true
      item-move-to-mine-cart-hopper: true